# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TestProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestProject
  react_native_path = "../node_modules/react-native"
  pod 'yoga', :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', :path => react_native_path, :subspecs => [
    'RCTImage', # Required For React Native 0.45.0+
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


end
